### ISSUE TITLE
Include mylocation.html file

### ISSUE THREAD

**Issue by nitinkumar30** [shivang21007/Number-Tracker#2]
Would you consider sharing the source code, if any, for the `mylocation.html` file in the `main.py` file of your project which states it'll automatically open.

**Comment by shivang21007** [comment]
@nitinkumar30 yes sure...

folitum module atomatically creater the file `mylocation.html` file. 
by this code -
``` 
import folium
map_location = folium.Map(location = [lat,lng], zoom_start=8)
folium.Marker([lat,lng], popup=number_location).add_to(map_location)
map_location.save("mylocation.html")

```
here ` lat , lng ` are the variables  storing values .
And webbrowser module open the file in browser -
``` 
import webbrowser
url = " realtive path  "  
webbrowser.open_new(url)
```

here insert the relative path of mylocation.html
