### ISSUE TITLE
main.py", line 3, in <module>     from key import keys ModuleNotFoundError: No module named 'key'

### ISSUE THREAD

**Issue by MrS3rv3r404** [shivang21007/Number-Tracker#3]
i have succesfully installed key module
But i found error again

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/Number-Tracker/main.py", line 3, in <module>
    from key import keys
ModuleNotFoundError: No module named 'key'

**Comment by shivang21007** [comment]
@MrS3rv3r404 yes, just make a file keys.py in the same directory and paste your opencage api key like that -

```
key = < your api key >
```

**Comment by MrS3rv3r404** [comment]
How to create key.py in termux?

**Comment by shivang21007** [comment]
just delete this line - " from key import keys"

and write there like that - 
```
key = < your api key >
```
make sure replace it with your api key

**Comment by MrS3rv3r404** [comment]
after write api key & delete line from key import keys i found error  
SyntaxError: invalid decimal literal

**Comment by MrS3rv3r404** [comment]
Thanks bro it's work but still not accurated for tracking

**Comment by shivang21007** [comment]
@MrS3rv3r404  Yes, It's not accurate bcoz privacy concerns but it gives you some imp. data about phone no. and location.

@MrS3rv3r404 Glad to know you find my project fun.
